### ISSUE TITLE
maven artifact is scala sdk

### ISSUE THREAD

**Issue by mattluce** [zoho/zohocrm-java-sdk-6.0#2]
The jar file at these coordinates appears to be the scala SDK, not the java SDK. It does not match the downloadable jar file.

repositories{
    maven { url "https://maven.zohodl.com" }
}
dependencies{
    implementation 'com.zoho.crm:zohocrmsdk-6-0:1.0.0'
}

**Comment by raja-k-7453** [comment]
@mattluce Please get in touch with [support@zohocrm.com](mailto:support@zohocrm.com), for further updates. We will follow up on this request, over there.

Thanks!
