### ISSUE TITLE
Java maven artifact is the scala version

### ISSUE THREAD

**Issue by Luthien-in-edhil** [zoho/zohocrm-java-sdk-6.0#3]
hi all, 

I ran into the same issue as described [in this closed ticket](https://github.com/zoho/zohocrm-java-sdk-6.0/issues/2): trying to use the Java version of the Zoho CRM SDK v6 in the pom file:

```
    <dependency>
      <groupId>com.zoho.crm</groupId>
      <artifactId>zohocrmsdk-6-0</artifactId>
      <version>1.0.0</version>
    </dependency>
```

results in it downloading the scala version instead (the scala one is actually version 2.0.0). 
This is because the Maven repository at https://repo1.maven.org/maven2/com/zoho/crm/zohocrmsdk-6-0/1.0.0/ contains the scala versions, but I don't know if anyone can upload files there. There is at least a correct [.jar](https://maven.zohodl.com/com/zoho/crm/zohocrmsdk-6-0/1.0.0/zohocrmsdk-6-0-1.0.0.jar) and [.pom](https://maven.zohodl.com/com/zoho/crm/zohocrmsdk-6-0/1.0.0/zohocrmsdk-6-0-1.0.0.pom) in Zoho's own maven.zohodl.com repository, so those can be used as a workaround.

**Comment by raja-k-7453** [comment]
Hi @Luthien-in-edhil, The [Maven repository](https://mvnrepository.com/artifact/com.zoho.crm/zohocrmsdk-6-0) contains the **Scala SDK** (**zohocrmsdk-6-0**). However, our Zoho Maven (https://maven.zohodl.com/) repository hosts the **Java SDK** (previously **zohocrmsdk-6-0**, currently renamed to **zohocrm-java-sdk-6-0** with an updated artifactId). 

When installing from the Maven repository using **zohocrmsdk-6-0**, the **Scala SDK**  will be installed unless you had first added the repository and then installed the SDK. Alternatively, if the **Scala SDK** is present in the cache, you will need to clear the cache before installing the **Java SDK**.

To avoid this confusion, we have updated the artifactId of the **Java SDK** to **zohocrm-java-sdk-6-0** in Zoho's Maven repository.  If you have already installed the **Scala SDK**, kindly add **zohocrm-java-sdk-6-0** to your pom.xml file and rebuild the project.  This action will uninstall the **Scala SDK** and replace it with the **Java SDK**.

Kindly refer [here](https://github.com/zoho/zohocrm-java-sdk-6.0/blob/beta/README.md) for more details.

**Comment by Luthien-in-edhil** [comment]
Hi @raja-7453 thanks for answering.

Thanks for renaming the artifactID in the Zoho Maven repository. Hopefully it is picked up then by maven, but that does not alter the fact (it's even documented on the Zoho website: [java version](https://www.zoho.com/crm/developer/docs/sdk/server-side/java-sdk.html) vs [scala version](https://www.zoho.com/crm/developer/docs/sdk/server-side/scala-sdk.html)) that **1.0.0** refers to the **JAVA** version, and hence the _**Maven**_ repository for [Zohozrmsdk-6-0@1.0.0](https://central.sonatype.com/artifact/com.zoho.crm/zohocrmsdk-6-0/1.0.0) should contain the **JAVA** version as well, all the more because the scala version is already present on [Zohozrmsdk-6-0@2.0.0](https://central.sonatype.com/artifact/com.zoho.crm/zohocrmsdk-6-0/2.0.0).

Until that issue is addressed, people looking for the java SDK will get the scala version instead.

**Comment by raja-k-7453** [comment]
Hi @Luthien-in-edhil We have updated our [help doc](https://www.zoho.com/crm/developer/docs/sdk/server-side/java-sdk.html) with the correct name for the JAR file. 

Please use **zohocrm-java-sdk-6-0** for [Java SDK](https://github.com/zoho/zohocrm-java-sdk-6.0/releases), and  **zohocrmsdk-6-0** for [Scala SDK](https://github.com/zoho/zohocrm-scala-sdk-6.0/releases).
