### ISSUE TITLE
PATCH Operations

### ISSUE THREAD

**Issue by gmcnicol** [zoho/zohocrm-java-sdk-6.0#8]
Could PATCH operations be introduced to the `records` package so calls to update records don't overwrite changes made elsewhere?

**Comment by raja-k-7453** [comment]
@gmcnicol Thanks for your contribution. Please clarify the use case and draft an email to [support@zohocrm.com](mailto:support@zohocrm.com). We will analyze the use case and follow up on this request, over there.

Thanks!
